[package]
name = "hydra-check"
version = "2.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
clap = { version = "4.5.20", features = ["derive"] }
flexi_logger = "0.29.3"
log = "0.4.22"
regex = "1.11.0"
scraper = "0.20.0"
